server:
  port: 9002

logging:
  level:
    pl.tt.storagemanager.storagemanager: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/storage

storagemanager:
  health-check:
    heartbeat: 10000

storage:
  protocol: http
  endpoint-url:
    health-check: /api/storage/state
